PAYMENT_CREDIT = "credit"
PAYMENT_DEBIT = "debit"
PAYMENT_PAYPAL = "paypal"
PAYMENT_METHODS = [PAYMENT_CREDIT, PAYMENT_DEBIT, PAYMENT_PAYPAL]

AUTH_SMS = "sms"
AUTH_EMAIL = "email"
AUTH_ROBOT = "robot"
AUTH_METHODS = [AUTH_SMS, AUTH_EMAIL, AUTH_ROBOT]

STATUS_PENDING = "pending"
STATUS_SUCCESS = "success"
STATUS_FAILED = "failed"

DEFAULT_AUTH = "default"
